[package]
name = "create-token-account"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "2.2.7"
solana-sdk = "2.2.2"
spl-token = "8.0.0"
spl-associated-token-account = "6.0.0"
dotenv = "0.15"
anyhow = "1.0"
serde_json = "1.0"
